In [49]:
# ----- imports -----
import pandas as pd
import sqlite3
print("All imports OK")

All imports OK

In [50]:
bus_df = pd.read_csv("../data/raw/ttc-bus-delay-data-2025.csv")
bus_df.head()

,_id,Date,Line,Time,Day,Station,Code,Min Delay,Min Gap,Bound,Vehicle
0,1,2025-01-01T00:00:00,102 MARKHAM ROAD,02:15,Wednesday,WARDEN STATION,MFESA,20,40,N,3442
1,2,2025-01-01T00:00:00,65 PARLIAMENT,02:15,Wednesday,KIPLING STATION,MFUS,0,0,NaN,0
2,3,2025-01-01T00:00:00,64 MAIN,02:40,Wednesday,BROADVIEW STATION,MFUI,0,0,NaN,8546
3,4,2025-01-01T00:00:00,100 FLEMINGDON PARK,02:43,Wednesday,OVERLEA AND THORNCLIFF,MFSAN,17,32,N,8693
4,5,2025-01-01T00:00:00,34 EGLINTON EAST,03:05,Wednesday,EGLINTON AND DON MILLS,MFUI,20,40,W,8801

In [51]:
bus_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 84145 entries, 0 to 84144
Data columns (total 11 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   _id        84145 non-null  int64
 1   Date       84145 non-null  object
 2   Line       83143 non-null  object
 3   Time       84145 non-null  object
 4   Day        84145 non-null  object
 5   Station    84145 non-null  object
 6   Code       84145 non-null  object
 7   Min Delay  84145 non-null  int64
 8   Min Gap    84145 non-null  int64
 9   Bound      67550 non-null  object
 10  Vehicle    84145 non-null  int64
dtypes: int64(4), object(7)
memory usage: 7.1+ MB

In [52]:
# check null values
bus_df.isna().sum()

_id              0
Date             0
Line          1002
Time             0
Day              0
Station          0
Code             0
Min Delay        0
Min Gap          0
Bound        16595
Vehicle          0
dtype: int64

In [53]:
# check duplicates
bus_df.duplicated().sum()

np.int64(0)

In [54]:
# drop numerical null values
clean_bus = bus_df.dropna(subset=["Line"]).copy()

# fill in categorical null values
clean_bus["Bound"] = clean_bus["Bound"].fillna("Unknown")

# date reformatting
clean_bus["Date"] = pd.to_datetime(clean_bus["Date"])
print(clean_bus[["Date", "Time"]].head())
print("-"*42)
# add features 
clean_bus["Month"] = clean_bus["Date"].dt.strftime("%Y-%m")
clean_bus["Hour"] = clean_bus["Time"].str.split(":").str[0]

print(clean_bus[["Date", "Month", "Hour", "Min Delay"]].head())

        Date   Time
0 2025-01-01  02:15
1 2025-01-01  02:15
2 2025-01-01  02:40
3 2025-01-01  02:43
4 2025-01-01  03:05
------------------------------------------
        Date    Month Hour  Min Delay
0 2025-01-01  2025-01   02         20
1 2025-01-01  2025-01   02          0
2 2025-01-01  2025-01   02          0
3 2025-01-01  2025-01   02         17
4 2025-01-01  2025-01   03         20

In [55]:
stcar_df = pd.read_csv("../data/raw/ttc-streetcar-delay-data-2025.csv")
stcar_df.head()

,_id,Date,Line,Time,Day,Station,Code,Min Delay,Min Gap,Bound,Vehicle
0,1,2025-01-01,504 KING,02:10,Wednesday,KING AND PARLIAMENT,MTSAN,10,20,W,4569
1,2,2025-01-01,506 CARLTON,02:50,Wednesday,COLLEGE AND HURON,MTAFR,34,49,E,4480
2,3,2025-01-01,504 KING,03:11,Wednesday,KING AND QUEEN EAST,MTIE,15,30,E,4629
3,4,2025-01-01,501 QUEEN,05:14,Wednesday,QUEEN AND DUFFERIN,MTAFR,36,55,E,4455
4,5,2025-01-01,504 KING,06:14,Wednesday,LESLIE CARHOUSE,MTVIS,10,20,E,4483

In [56]:
stcar_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20740 entries, 0 to 20739
Data columns (total 11 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   _id        20740 non-null  int64
 1   Date       20740 non-null  object
 2   Line       20444 non-null  object
 3   Time       20740 non-null  object
 4   Day        20740 non-null  object
 5   Station    20740 non-null  object
 6   Code       20739 non-null  object
 7   Min Delay  20740 non-null  int64
 8   Min Gap    20740 non-null  int64
 9   Bound      16258 non-null  object
 10  Vehicle    20740 non-null  int64
dtypes: int64(4), object(7)
memory usage: 1.7+ MB

In [57]:
# check null values
stcar_df.isnull().sum()

_id             0
Date            0
Line          296
Time            0
Day             0
Station         0
Code            1
Min Delay       0
Min Gap         0
Bound        4482
Vehicle         0
dtype: int64

In [58]:
# check duplicate
stcar_df.duplicated().sum()

np.int64(0)

In [59]:
# drop numerical null values
clean_stcar = stcar_df.dropna(subset=["Line"]).copy()

# fill in categorical null values
clean_stcar["Bound"] = clean_stcar["Bound"].fillna("Unknown")
clean_stcar["Code"] = clean_stcar["Code"].fillna("Uncoded")

# date reformatting
clean_stcar["Date"] = pd.to_datetime(clean_stcar["Date"])
print(clean_stcar[["Date", "Time"]].head())
print("-"*42)
# add features 
clean_stcar["Month"] = clean_stcar["Date"].dt.strftime("%Y-%m")
clean_stcar["Hour"] = clean_stcar["Time"].str.split(":").str[0]

print(clean_stcar[["Date", "Month", "Hour", "Min Delay"]].head())

        Date   Time
0 2025-01-01  02:10
1 2025-01-01  02:50
2 2025-01-01  03:11
3 2025-01-01  05:14
4 2025-01-01  06:14
------------------------------------------
        Date    Month Hour  Min Delay
0 2025-01-01  2025-01   02         10
1 2025-01-01  2025-01   02         34
2 2025-01-01  2025-01   03         15
3 2025-01-01  2025-01   05         36
4 2025-01-01  2025-01   06         10

In [60]:
subway_df = pd.read_csv("../data/raw/ttc-subway-delay-data-2025.csv")
subway_df.head()

,_id,Date,Time,Day,Station,Code,Min Delay,Min Gap,Bound,Line,Vehicle
0,1,2025-01-01,02:10,Wednesday,BATHURST STATION,MUSAN,5,9,E,BD,5227
1,2,2025-01-01,02:30,Wednesday,DUNDAS STATION,MUIRS,0,0,NaN,YU,0
2,3,2025-01-01,02:32,Wednesday,BROADVIEW STATION,PUMST,0,0,E,BD,0
3,4,2025-01-01,02:58,Wednesday,KEELE STATION,EUSC,0,0,W,BD,5293
4,5,2025-01-01,02:58,Wednesday,COXWELL STATION,SUAE,0,0,NaN,BD,0

In [61]:
subway_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38018 entries, 0 to 38017
Data columns (total 11 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   _id        38018 non-null  int64
 1   Date       38018 non-null  object
 2   Time       38018 non-null  object
 3   Day        38018 non-null  object
 4   Station    38018 non-null  object
 5   Code       38018 non-null  object
 6   Min Delay  38018 non-null  int64
 7   Min Gap    38018 non-null  int64
 8   Bound      24592 non-null  object
 9   Line       37891 non-null  object
 10  Vehicle    38018 non-null  int64
dtypes: int64(4), object(7)
memory usage: 3.2+ MB

In [62]:
# check null values
subway_df.isnull().sum()

_id              0
Date             0
Time             0
Day              0
Station          0
Code             0
Min Delay        0
Min Gap          0
Bound        13426
Line           127
Vehicle          0
dtype: int64

In [63]:
# check duplicates
subway_df.duplicated().sum()

np.int64(0)

In [64]:
# drop numerical null values
clean_subway = subway_df.dropna(subset=["Line"]).copy()

# fill in categorical null values
clean_subway["Bound"] = subway_df["Bound"].fillna("Unknown")

# date reformatting
clean_subway["Date"] = pd.to_datetime(clean_subway["Date"])
print(clean_subway[["Date", "Time"]].head())
print("-"*42)
# add features 
clean_subway["Month"] = clean_subway["Date"].dt.strftime("%Y-%m")
clean_subway["Hour"] = clean_subway["Time"].str.split(":").str[0]

print(clean_subway[["Date", "Month", "Hour", "Min Delay"]].head())

        Date   Time
0 2025-01-01  02:10
1 2025-01-01  02:30
2 2025-01-01  02:32
3 2025-01-01  02:58
4 2025-01-01  02:58
------------------------------------------
        Date    Month Hour  Min Delay
0 2025-01-01  2025-01   02          5
1 2025-01-01  2025-01   02          0
2 2025-01-01  2025-01   02          0
3 2025-01-01  2025-01   02          0
4 2025-01-01  2025-01   02          0

In [65]:
conn = sqlite3.connect("../sql/TTC_delay.db")

clean_bus.to_sql(
    name="bus_delays",
    con=conn,
    if_exists="replace",
    index=False
)
clean_stcar.to_sql(
    name="streetcar_delays",
    con=conn,
    if_exists="replace",
    index=False
)
clean_subway.to_sql(
    name="subway_delays",
    con=conn,
    if_exists="replace",
    index=False
)

conn.close()
print("Loaded successfully.")

Loaded successfully.

In [66]:
conn = sqlite3.connect("../sql/TTC_delay.db")

for table in ["bus_delays", "streetcar_delays", "subway_delays"]:
    print(f"\n{table}")
    print(pd.read_sql(f"PRAGMA table_info({table})", conn))
    print(pd.read_sql(f"""
    SELECT COUNT (*) AS rows 
    FROM {table}
    """,conn))

conn.close()

bus_delays
    cid       name       type  notnull dflt_value  pk
0     0        _id    INTEGER        0       None   0
1     1       Date  TIMESTAMP        0       None   0
2     2       Line       TEXT        0       None   0
3     3       Time       TEXT        0       None   0
4     4        Day       TEXT        0       None   0
5     5    Station       TEXT        0       None   0
6     6       Code       TEXT        0       None   0
7     7  Min Delay    INTEGER        0       None   0
8     8    Min Gap    INTEGER        0       None   0
9     9      Bound       TEXT        0       None   0
10   10    Vehicle    INTEGER        0       None   0
11   11      Month       TEXT        0       None   0
12   12       Hour       TEXT        0       None   0
    rows
0  83143

streetcar_delays
    cid       name       type  notnull dflt_value  pk
0     0        _id    INTEGER        0       None   0
1     1       Date  TIMESTAMP        0       None   0
2     2       Line       TEXT        0       None   0
3     3       Time       TEXT        0       None   0
4     4        Day       TEXT        0       None   0
5     5    Station       TEXT        0       None   0
6     6       Code       TEXT        0       None   0
7     7  Min Delay    INTEGER        0       None   0
8     8    Min Gap    INTEGER        0       None   0
9     9      Bound       TEXT        0       None   0
10   10    Vehicle    INTEGER        0       None   0
11   11      Month       TEXT        0       None   0
12   12       Hour       TEXT        0       None   0
    rows
0  20444

subway_delays
    cid       name       type  notnull dflt_value  pk
0     0        _id    INTEGER        0       None   0
1     1       Date  TIMESTAMP        0       None   0
2     2       Time       TEXT        0       None   0
3     3        Day       TEXT        0       None   0
4     4    Station       TEXT        0       None   0
5     5       Code       TEXT        0       None   0
6     6  Min Delay    INTEGER        0       None   0
7     7    Min Gap    INTEGER        0       None   0
8     8      Bound       TEXT        0       None   0
9     9       Line       TEXT        0       None   0
10   10    Vehicle    INTEGER        0       None   0
11   11      Month       TEXT        0       None   0
12   12       Hour       TEXT        0       None   0
    rows
0  37891

In [67]:
conn = sqlite3.connect("../sql/TTC_delay.db")

conn.execute("DROP TABLE IF EXISTS all_delays")

conn.execute("""
CREATE TABLE all_delays AS

SELECT
    'bus' AS transit_mode,
    date,
    time,
    day,
    month,
    hour,
    line,
    station,
    code,
    [Min Delay] AS min_delay,
    [Min Gap] AS min_gap,
    bound,
    vehicle
FROM bus_delays

UNION ALL

SELECT
    'streetcar' AS transit_mode,
    date,
    time,
    day,
    month,
    hour,
    line,
    station,
    code,
    [Min Delay] AS min_delay,
    [Min Gap] AS min_gap,
    bound,
    vehicle
FROM streetcar_delays

UNION ALL

SELECT
    'subway' AS transit_mode,
    date,
    time,
    day,
    month,
    hour,
    line,
    station,
    code,
    [Min Delay] AS min_delay,
    [Min Gap] AS min_gap,
    bound,
    vehicle
FROM subway_delays
""")

conn.commit()

mode_df = pd.read_sql("""
SELECT transit_mode, COUNT (*) AS rows
FROM all_delays
GROUP BY transit_mode
""", conn)

conn.close()
print(mode_df)

  transit_mode   rows
0          bus  83143
1    streetcar  20444
2       subway  37891

In [68]:
conn = sqlite3.connect("../sql/TTC_delay.db")

total_rows_df = pd.read_sql("""
SELECT COUNT (*) AS total_rows
FROM all_delays
""", conn)

conn.close()
print(total_rows_df)

   total_rows
0      141478

In [69]:
# load lookup sheets
bus_lookup = pd.read_csv("../data/raw/ttc-bus-delay-data-lookup.csv", encoding="cp1252")

bus_lookup.head()

   _id   CODE   DESCRIPTION
0    1    EFB          BODY
1    2  EFCAN  CANCELLATION
2    3    EFD         DOORS
3    4   EFDB   DISC BRAKES
4    5   EFHV  HIGH VOLTAGE

In [70]:
stcar_lookup = pd.read_csv("../data/raw/ttc-streetcar-delay-data-lookup.csv", encoding="utf-8")

stcar_lookup.head()

   _id  CODE            DESCRIPTION
0    1  ETAC                   HVAC
1    2  ETAR    ARTICULATION (ALRV)
2    3  ETAX  AUXILARY POWER SUPPLY
3    4  ETBO                   BODY
4    5  ETCA         COMPRESSED AIR

In [71]:
subway_lookup = pd.read_csv("../data/raw/ttc-subway-delay-data-lookup.csv", encoding="utf-8")

subway_lookup.head()

   _id   CODE          DESCRIPTION
0    1   EUAC     AIR CONDITIONING
1    2   EUAL  ALTERNATING CURRENT
2    3  EUATC   ATC RC&S EQUIPMENT
3    4   EUBK               BRAKES
4    5   EUBO                 BODY

In [72]:
for df in [bus_lookup, stcar_lookup, subway_lookup]:
    df.columns = df.columns.str.lower()

# add transit_mode to prevent clashing
bus_lookup["transit_mode"] = "bus"
stcar_lookup["transit_mode"] = "streetcar"
subway_lookup["transit_mode"] = "subway"

lookup_df = pd.concat([bus_lookup, stcar_lookup, subway_lookup], ignore_index=True)
lookup_df = lookup_df.drop_duplicates(subset=["transit_mode", "code"]).copy()

conn = sqlite3.connect("../sql/TTC_delay.db")
lookup_df.to_sql(
    name="delay_codes",
    con=conn,
    if_exists="replace",
    index=False
)

conn.close()
print("Combined lookup table successfully.")
print(f"{len(lookup_df)} unique rows")

Combined lookup table successfully.
271 unique rows

In [73]:
conn = sqlite3.connect("../sql/TTC_delay.db")

conn.execute("DROP VIEW IF EXISTS view_delays_by_mode")

conn.execute("""
CREATE VIEW view_delays_by_mode AS
SELECT
    transit_mode,
    COUNT (*) AS total_incidents,
    SUM(min_delay) AS total_delay_minutes,
    ROUND(AVG(min_delay), 2) AS avg_delay_minutes,
    MAX(min_delay) AS max_delay_minutes
FROM all_delays
GROUP BY transit_mode;
""")

conn.execute("DROP VIEW IF EXISTS view_delays_by_month")
conn.execute("""
CREATE VIEW view_delays_by_month AS
SELECT
    month,
    transit_mode,
    COUNT (*) AS total_incidents,
    SUM(min_delay) AS total_delay_minutes,
    ROUND(AVG(min_delay), 2) AS avg_delay_minutes
FROM all_delays
GROUP BY month, transit_mode;
""")

conn.execute("DROP VIEW IF EXISTS view_delays_by_hour")
conn.execute("""
CREATE VIEW view_delays_by_hour AS
SELECT
    hour,
    transit_mode,
    COUNT (*) AS total_incidents,
    SUM(min_delay) AS total_delay_minutes,
    ROUND(AVG(min_delay), 2) AS avg_delay_minutes
FROM all_delays
GROUP BY hour, transit_mode;
""")

conn.execute("DROP VIEW IF EXISTS view_top_lines")
conn.execute("""
CREATE VIEW view_top_lines AS
SELECT
    transit_mode,
    line,
    COUNT (*) AS total_incidents,
    SUM(min_delay) AS total_delay_minutes,
    ROUND(AVG(min_delay), 2) AS avg_delay_minutes
FROM all_delays
GROUP BY transit_mode, line
ORDER BY total_delay_minutes DESC;
""")

conn.execute("DROP VIEW IF EXISTS view_delay_reasons")
conn.execute("""
CREATE VIEW view_delay_reasons AS
SELECT
    a.transit_mode,
    COALESCE(b.description, 'Uncoded/Other') AS delay_reasons,
    COUNT (*) AS total_incidents,
    SUM(a.min_delay) AS total_delay_minutes,
    ROUND(AVG(a.min_delay), 2) AS avg_delay_minutes
FROM all_delays a
LEFT JOIN delay_codes b
    ON a.code = b.code AND a.transit_mode = b.transit_mode
GROUP BY a.transit_mode, delay_reasons
ORDER BY total_delay_minutes DESC;
""")

conn.commit()
conn.close()
print("Views updated successfully.")

Views updated successfully.